### ISSUE TITLE
Why you use build Runner

### ISSUE THREAD

**Issue by Scienticious** [red-star25/bloc_blog#1]
Hi Nakum,

https://dhruvnakum.xyz/flutter-bloc-a-complete-guide
I am following your above-mentioned article.
You explained so well , and  I am also implementing the bloc pattern by following your this sample.

Would you please explain why you use build Runner in your project?

Thanks

**Comment by red-star25** [comment]
It's basically for code generation. If you see in the `lib>data>models` There is a Model class called `weather.g.dart` which is generated with the help of `json_serializable` and `build_runner`. Hope this answers your question.
